-- Tabela para Notificações (Sprint 9)
CREATE TABLE IF NOT EXISTS public.notificacoes (
    id bigint generated by default as identity primary key,
    projeto_id bigint references public.projetos(id) on delete cascade,
    tipo text not null, -- 'SUCESSO', 'ERRO', 'ALERTA', 'INFO'
    titulo text not null,
    mensagem text not null,
    lida boolean default false,
    criado_em timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.notificacoes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON "public"."notificacoes"
AS PERMISSIVE FOR SELECT TO public USING (true);

CREATE POLICY "Enable insert for all users" ON "public"."notificacoes"
AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
