-- Tabela para armazenar as análises temporais comparativas de missões (Sprint 8)
CREATE TABLE IF NOT EXISTS public.comparacoes_temporais (
    id bigint generated by default as identity primary key,
    
    -- Amarras Arquiteturais
    fazenda_id bigint references public.fazendas(id) on delete cascade not null,
    talhao_id bigint references public.talhoes(id) on delete cascade not null,
    
    -- Missões sendo comparadas
    missao_antiga_id bigint references public.projetos(id) on delete cascade not null,
    missao_nova_id bigint references public.projetos(id) on delete cascade not null,
    
    -- Deltas e Indicadores de Evolução (Hectares)
    delta_area_recuperada_ha numeric(10,2) default 0,
    delta_area_degradada_ha numeric(10,2) default 0,
    
    -- Vigor Geral e Score
    ganho_vigor_percentual numeric(5,2) default 0,
    
    -- NLP / Resposta da IA (O tratamento funcionou?)
    laudo_texto text,
    status_evolucao text check (status_evolucao in ('MELHORA', 'ESTAVEL', 'PIORA')),
    
    data_comparacao timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS (Opcional no momento)
ALTER TABLE public.comparacoes_temporais ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON "public"."comparacoes_temporais"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

CREATE POLICY "Enable insert for all users" ON "public"."comparacoes_temporais"
AS PERMISSIVE FOR INSERT
TO public
WITH CHECK (true);

-- Indexação para ganho de velocidade no Dashboard da Fazenda
CREATE INDEX IF NOT EXISTS idx_comparacoes_fazenda ON public.comparacoes_temporais(fazenda_id);
CREATE INDEX IF NOT EXISTS idx_comparacoes_talhao ON public.comparacoes_temporais(talhao_id);
