-- ==========================================
-- SCRIPT DE CORREÇÃO: TABELA DE DIAGNÓSTICO IA E COMPARAÇÃO
-- ==========================================

-- 1. Cria a tabela de diagnosticos da IA
CREATE TABLE IF NOT EXISTS public.diagnosticos_ia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projeto_id BIGINT REFERENCES public.projetos(id) ON DELETE CASCADE,
    saude_geral TEXT,
    alto_vigor_pct NUMERIC,
    medio_vigor_pct NUMERIC,
    baixo_vigor_pct NUMERIC,
    nivel_confianca NUMERIC,
    anomalias_detectadas JSONB DEFAULT '[]'::jsonb,
    recomendacoes_tecnicas TEXT,
    prioridade_geral TEXT,
    intervencoes_sugeridas JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(projeto_id)
);

-- 2. Cria a tabela de comparações temporais
CREATE TABLE IF NOT EXISTS public.comparacoes_temporais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fazenda_id BIGINT REFERENCES public.fazendas(id) ON DELETE CASCADE,
    talhao_id BIGINT REFERENCES public.talhoes(id) ON DELETE CASCADE,
    missao_antiga_id BIGINT REFERENCES public.projetos(id) ON DELETE CASCADE,
    missao_nova_id BIGINT REFERENCES public.projetos(id) ON DELETE CASCADE,
    delta_area_recuperada_ha NUMERIC,
    delta_area_degradada_ha NUMERIC,
    ganho_vigor_percentual NUMERIC,
    laudo_texto TEXT,
    status_evolucao TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS nas tabelas novas
ALTER TABLE public.diagnosticos_ia ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comparacoes_temporais ENABLE ROW LEVEL SECURITY;

-- Políticas God Mode para as novas tabelas
DROP POLICY IF EXISTS "Deus_da_Plataforma_Full_Access_Diagnosticos" ON public.diagnosticos_ia;
CREATE POLICY "Deus_da_Plataforma_Full_Access_Diagnosticos" ON public.diagnosticos_ia FOR ALL USING (EXISTS (SELECT 1 FROM perfis_usuarios WHERE id = auth.uid() AND perfil = 'admin'));

DROP POLICY IF EXISTS "Deus_da_Plataforma_Full_Access_Comparacoes" ON public.comparacoes_temporais;
CREATE POLICY "Deus_da_Plataforma_Full_Access_Comparacoes" ON public.comparacoes_temporais FOR ALL USING (EXISTS (SELECT 1 FROM perfis_usuarios WHERE id = auth.uid() AND perfil = 'admin'));

-- Atualizar o cache de schema da API do Supabase
NOTIFY pgrst, 'reload schema';
