-- ==========================================
-- SCRIPT DE CORREÇÃO FINAL: TABELAS DE LOG E NOTIFICAÇÕES
-- ==========================================

-- 1. Colunas extras na mission_jobs para o retry system
ALTER TABLE public.mission_jobs ADD COLUMN IF NOT EXISTS tentativas INTEGER DEFAULT 0;
ALTER TABLE public.mission_jobs ADD COLUMN IF NOT EXISTS max_tentativas INTEGER DEFAULT 3;

-- 2. Tabela de logs do processo (process_logs)
CREATE TABLE IF NOT EXISTS public.process_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id UUID REFERENCES public.mission_jobs(id) ON DELETE CASCADE,
  projeto_id BIGINT REFERENCES public.projetos(id) ON DELETE CASCADE,
  acao TEXT,
  status TEXT,
  mensagem TEXT,
  duracao_ms INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Tabela de notificações
CREATE TABLE IF NOT EXISTS public.notificacoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  projeto_id BIGINT REFERENCES public.projetos(id) ON DELETE CASCADE,
  tipo TEXT,
  titulo TEXT,
  mensagem TEXT,
  lida BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS God Mode para logs e notificacoes
ALTER TABLE public.process_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Deus_da_Plataforma_Full_Access_ProcessLogs" ON public.process_logs;
CREATE POLICY "Deus_da_Plataforma_Full_Access_ProcessLogs" ON public.process_logs FOR ALL USING (EXISTS (SELECT 1 FROM perfis_usuarios WHERE id = auth.uid() AND perfil = 'admin'));

ALTER TABLE public.notificacoes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Deus_da_Plataforma_Full_Access_Notificacoes" ON public.notificacoes;
CREATE POLICY "Deus_da_Plataforma_Full_Access_Notificacoes" ON public.notificacoes FOR ALL USING (EXISTS (SELECT 1 FROM perfis_usuarios WHERE id = auth.uid() AND perfil = 'admin'));

-- Atualizar cache da API
NOTIFY pgrst, 'reload schema';
