-- ==========================================
-- SCRIPT DE INFRAESTRUTURA: CRIAÇÃO DAS TABELAS NUCLEARES (SPRINT 2/3)
-- ==========================================

-- 1. Empresas
CREATE TABLE IF NOT EXISTS public.empresas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  cnpj TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Agrônomos
CREATE TABLE IF NOT EXISTS public.agronomos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT REFERENCES public.empresas(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  registro_crea TEXT,
  email TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Fazendas
CREATE TABLE IF NOT EXISTS public.fazendas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id BIGINT REFERENCES public.clientes(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  cidade TEXT,
  estado TEXT,
  area_ha DECIMAL,
  frequencia_monitoramento INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Talhões (Requisita Fazenda)
CREATE TABLE IF NOT EXISTS public.talhoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fazenda_id BIGINT REFERENCES public.fazendas(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  cultura TEXT,
  area_hectares DECIMAL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Pragas
CREATE TABLE IF NOT EXISTS public.pragas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  gravidade TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Intervenções
CREATE TABLE IF NOT EXISTS public.intervencoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  talhao_id BIGINT REFERENCES public.talhoes(id) ON DELETE CASCADE,
  praga_id BIGINT REFERENCES public.pragas(id) ON DELETE SET NULL,
  tipo TEXT NOT NULL,
  data_realizacao DATE,
  status TEXT DEFAULT 'PENDENTE',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ATUALIZAR MODO DEUS PARA ABRAÇAR ESTAS TABELAS
ALTER TABLE public.empresas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Deus_da_Plataforma_Full_Access_Empresas" ON public.empresas;
CREATE POLICY "Deus_da_Plataforma_Full_Access_Empresas" ON public.empresas FOR ALL USING (EXISTS (SELECT 1 FROM perfis_usuarios WHERE id = auth.uid() AND perfil = 'admin'));

ALTER TABLE public.agronomos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Deus_da_Plataforma_Full_Access_Agronomos" ON public.agronomos;
CREATE POLICY "Deus_da_Plataforma_Full_Access_Agronomos" ON public.agronomos FOR ALL USING (EXISTS (SELECT 1 FROM perfis_usuarios WHERE id = auth.uid() AND perfil = 'admin'));

ALTER TABLE public.fazendas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Deus_da_Plataforma_Full_Access_Fazendas" ON public.fazendas;
CREATE POLICY "Deus_da_Plataforma_Full_Access_Fazendas" ON public.fazendas FOR ALL USING (EXISTS (SELECT 1 FROM perfis_usuarios WHERE id = auth.uid() AND perfil = 'admin'));

ALTER TABLE public.talhoes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Deus_da_Plataforma_Full_Access_Talhoes" ON public.talhoes;
CREATE POLICY "Deus_da_Plataforma_Full_Access_Talhoes" ON public.talhoes FOR ALL USING (EXISTS (SELECT 1 FROM perfis_usuarios WHERE id = auth.uid() AND perfil = 'admin'));

ALTER TABLE public.pragas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Deus_da_Plataforma_Full_Access_Pragas" ON public.pragas;
CREATE POLICY "Deus_da_Plataforma_Full_Access_Pragas" ON public.pragas FOR ALL USING (EXISTS (SELECT 1 FROM perfis_usuarios WHERE id = auth.uid() AND perfil = 'admin'));

ALTER TABLE public.intervencoes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Deus_da_Plataforma_Full_Access_Intervencoes" ON public.intervencoes;
CREATE POLICY "Deus_da_Plataforma_Full_Access_Intervencoes" ON public.intervencoes FOR ALL USING (EXISTS (SELECT 1 FROM perfis_usuarios WHERE id = auth.uid() AND perfil = 'admin'));
