-- ==========================================
-- SCRIPT DE CORREÇÃO: BUCKET E TABELAS DE UPLOAD/PROCESSAMENTO
-- ==========================================

-- 1. Storage Bucket
INSERT INTO storage.buckets (id, name, public) VALUES ('missoes', 'missoes', true) ON CONFLICT DO NOTHING;

DROP POLICY IF EXISTS "Deus_da_Plataforma_Full_Access_Storage" ON storage.objects;
CREATE POLICY "Deus_da_Plataforma_Full_Access_Storage" ON storage.objects FOR ALL USING (bucket_id = 'missoes');

-- 2. Tabela mission_jobs
CREATE TABLE IF NOT EXISTS public.mission_jobs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  projeto_id BIGINT REFERENCES public.projetos(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'ENFILEIRADO',
  etapa_atual TEXT DEFAULT 'UPLOAD_CONCLUIDO',
  started_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE,
  error_log TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Tabela arquivos_projeto
CREATE TABLE IF NOT EXISTS public.arquivos_projeto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  projeto_id BIGINT REFERENCES public.projetos(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  caminho TEXT NOT NULL,
  bucket TEXT NOT NULL,
  url TEXT NOT NULL,
  tipo TEXT,
  tamanho BIGINT,
  origem TEXT,
  status TEXT,
  processado BOOLEAN DEFAULT false,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS God Mode
ALTER TABLE public.mission_jobs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Deus_da_Plataforma_Full_Access_MissionJobs" ON public.mission_jobs;
CREATE POLICY "Deus_da_Plataforma_Full_Access_MissionJobs" ON public.mission_jobs FOR ALL USING (EXISTS (SELECT 1 FROM perfis_usuarios WHERE id = auth.uid() AND perfil = 'admin'));

ALTER TABLE public.arquivos_projeto ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Deus_da_Plataforma_Full_Access_Arquivos" ON public.arquivos_projeto;
CREATE POLICY "Deus_da_Plataforma_Full_Access_Arquivos" ON public.arquivos_projeto FOR ALL USING (EXISTS (SELECT 1 FROM perfis_usuarios WHERE id = auth.uid() AND perfil = 'admin'));

-- Atualizar o cache de schema da API do Supabase
NOTIFY pgrst, 'reload schema';
