-- ==========================================
-- SCRIPT DE MIGRAÇÃO: MONITORAMENTO INTELIGENTE
-- Transformando Projetos em Monitoramentos Híbridos e IoT
-- ==========================================

-- 1. Evoluindo a tabela de Projetos para Monitoramentos Híbridos
-- Projetos agora podem ser do tipo DRONE, SATELITE, ou IOT
-- Eles passam a pertencer a um Talhão
ALTER TABLE public.projetos 
ADD COLUMN IF NOT EXISTS talhao_id BIGINT REFERENCES public.talhoes(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS fonte_captura TEXT DEFAULT 'DRONE', -- 'DRONE', 'SATELITE', 'IOT'
ADD COLUMN IF NOT EXISTS bbox_geojson JSONB, -- Para salvar o Bounding Box extraído via EXIF
ADD COLUMN IF NOT EXISTS resumo_ia TEXT; -- Resumo executivo estruturado da IA

-- 2. Criando Tabela para Dados IoT (Pluviômetros, Sensores)
CREATE TABLE IF NOT EXISTS public.dados_iot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    talhao_id BIGINT REFERENCES public.talhoes(id) ON DELETE CASCADE,
    device_id TEXT,
    tipo_sensor TEXT NOT NULL, -- ex: 'PLUVIOMETRO', 'UMIDADE_SOLO', 'TEMPERATURA'
    valor DECIMAL NOT NULL,
    unidade TEXT, -- ex: 'mm', '%', '°C'
    data_leitura TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Atualizando RLS para a nova tabela
ALTER TABLE public.dados_iot ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Anon_Bypass_IoT" ON public.dados_iot;
CREATE POLICY "Anon_Bypass_IoT" ON public.dados_iot FOR ALL USING (true) WITH CHECK (true);

-- 4. Notificar PostgREST para recarregar o schema
NOTIFY pgrst, 'reload schema';
